/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PinsRouteImport } from './routes/pins'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as PagesIndexRouteImport } from './routes/pages.index'
import { Route as PagesIdRouteImport } from './routes/pages.$id'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SitesStyleSetupRouteImport } from './routes/sites.style-setup'
import { Route as ApiPublicCronCrawlRouteImport } from './routes/api/public/cron/crawl'
import { Route as ApiPublicCronImagesRouteImport } from './routes/api/public/cron/images'
import { Route as ApiPublicCronMaterializeRouteImport } from './routes/api/public/cron/materialize'
import { Route as ApiPublicCronPinterestTokenRefreshRouteImport } from './routes/api/public/cron/pinterest-token-refresh'
import { Route as ApiPublicCronPublishRouteImport } from './routes/api/public/cron/publish'
import { Route as ApiPublicCronSerpRouteImport } from './routes/api/public/cron/serp'
import { Route as ApiPublicCronTierCheckRouteImport } from './routes/api/public/cron/tier-check'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google.callback'
import { Route as ApiPublicPinterestCallbackRouteImport } from './routes/api/public/pinterest.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PinsRoute = PinsRouteImport.update({
  id: '/pins',
  path: '/pins',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIdRoute = PagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesStyleSetupRoute = SitesStyleSetupRouteImport.update({
  id: '/style-setup',
  path: '/style-setup',
  getParentRoute: () => SitesRoute,
} as any)
const ApiPublicCronCrawlRoute = ApiPublicCronCrawlRouteImport.update({
  id: '/api/public/cron/crawl',
  path: '/api/public/cron/crawl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronImagesRoute = ApiPublicCronImagesRouteImport.update({
  id: '/api/public/cron/images',
  path: '/api/public/cron/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronMaterializeRoute =
  ApiPublicCronMaterializeRouteImport.update({
    id: '/api/public/cron/materialize',
    path: '/api/public/cron/materialize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPinterestTokenRefreshRoute =
  ApiPublicCronPinterestTokenRefreshRouteImport.update({
    id: '/api/public/cron/pinterest-token-refresh',
    path: '/api/public/cron/pinterest-token-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPublishRoute = ApiPublicCronPublishRouteImport.update({
  id: '/api/public/cron/publish',
  path: '/api/public/cron/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSerpRoute = ApiPublicCronSerpRouteImport.update({
  id: '/api/public/cron/serp',
  path: '/api/public/cron/serp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronTierCheckRoute = ApiPublicCronTierCheckRouteImport.update({
  id: '/api/public/cron/tier-check',
  path: '/api/public/cron/tier-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPinterestCallbackRoute =
  ApiPublicPinterestCallbackRouteImport.update({
    id: '/api/public/pinterest/callback',
    path: '/api/public/pinterest/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boards': typeof BoardsRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/keywords': typeof KeywordsRoute
  '/logs': typeof LogsRoute
  '/onboarding': typeof OnboardingRoute
  '/pins': typeof PinsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sites': typeof SitesRouteWithChildren
  '/pages/$id': typeof PagesIdRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/sites/style-setup': typeof SitesStyleSetupRoute
  '/pages/': typeof PagesIndexRoute
  '/api/public/cron/crawl': typeof ApiPublicCronCrawlRoute
  '/api/public/cron/images': typeof ApiPublicCronImagesRoute
  '/api/public/cron/materialize': typeof ApiPublicCronMaterializeRoute
  '/api/public/cron/pinterest-token-refresh': typeof ApiPublicCronPinterestTokenRefreshRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/cron/serp': typeof ApiPublicCronSerpRoute
  '/api/public/cron/tier-check': typeof ApiPublicCronTierCheckRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/pinterest/callback': typeof ApiPublicPinterestCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boards': typeof BoardsRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/keywords': typeof KeywordsRoute
  '/logs': typeof LogsRoute
  '/onboarding': typeof OnboardingRoute
  '/pins': typeof PinsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sites': typeof SitesRouteWithChildren
  '/pages/$id': typeof PagesIdRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/sites/style-setup': typeof SitesStyleSetupRoute
  '/pages': typeof PagesIndexRoute
  '/api/public/cron/crawl': typeof ApiPublicCronCrawlRoute
  '/api/public/cron/images': typeof ApiPublicCronImagesRoute
  '/api/public/cron/materialize': typeof ApiPublicCronMaterializeRoute
  '/api/public/cron/pinterest-token-refresh': typeof ApiPublicCronPinterestTokenRefreshRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/cron/serp': typeof ApiPublicCronSerpRoute
  '/api/public/cron/tier-check': typeof ApiPublicCronTierCheckRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/pinterest/callback': typeof ApiPublicPinterestCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boards': typeof BoardsRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/keywords': typeof KeywordsRoute
  '/logs': typeof LogsRoute
  '/onboarding': typeof OnboardingRoute
  '/pins': typeof PinsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sites': typeof SitesRouteWithChildren
  '/pages/$id': typeof PagesIdRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/sites/style-setup': typeof SitesStyleSetupRoute
  '/pages/': typeof PagesIndexRoute
  '/api/public/cron/crawl': typeof ApiPublicCronCrawlRoute
  '/api/public/cron/images': typeof ApiPublicCronImagesRoute
  '/api/public/cron/materialize': typeof ApiPublicCronMaterializeRoute
  '/api/public/cron/pinterest-token-refresh': typeof ApiPublicCronPinterestTokenRefreshRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/cron/serp': typeof ApiPublicCronSerpRoute
  '/api/public/cron/tier-check': typeof ApiPublicCronTierCheckRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/pinterest/callback': typeof ApiPublicPinterestCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/boards'
    | '/dashboard'
    | '/insights'
    | '/keywords'
    | '/logs'
    | '/onboarding'
    | '/pins'
    | '/schedule'
    | '/sitemap.xml'
    | '/sites'
    | '/pages/$id'
    | '/settings/integrations'
    | '/sites/style-setup'
    | '/pages/'
    | '/api/public/cron/crawl'
    | '/api/public/cron/images'
    | '/api/public/cron/materialize'
    | '/api/public/cron/pinterest-token-refresh'
    | '/api/public/cron/publish'
    | '/api/public/cron/serp'
    | '/api/public/cron/tier-check'
    | '/api/public/google/callback'
    | '/api/public/pinterest/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/boards'
    | '/dashboard'
    | '/insights'
    | '/keywords'
    | '/logs'
    | '/onboarding'
    | '/pins'
    | '/schedule'
    | '/sitemap.xml'
    | '/sites'
    | '/pages/$id'
    | '/settings/integrations'
    | '/sites/style-setup'
    | '/pages'
    | '/api/public/cron/crawl'
    | '/api/public/cron/images'
    | '/api/public/cron/materialize'
    | '/api/public/cron/pinterest-token-refresh'
    | '/api/public/cron/publish'
    | '/api/public/cron/serp'
    | '/api/public/cron/tier-check'
    | '/api/public/google/callback'
    | '/api/public/pinterest/callback'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/boards'
    | '/dashboard'
    | '/insights'
    | '/keywords'
    | '/logs'
    | '/onboarding'
    | '/pins'
    | '/schedule'
    | '/sitemap.xml'
    | '/sites'
    | '/pages/$id'
    | '/settings/integrations'
    | '/sites/style-setup'
    | '/pages/'
    | '/api/public/cron/crawl'
    | '/api/public/cron/images'
    | '/api/public/cron/materialize'
    | '/api/public/cron/pinterest-token-refresh'
    | '/api/public/cron/publish'
    | '/api/public/cron/serp'
    | '/api/public/cron/tier-check'
    | '/api/public/google/callback'
    | '/api/public/pinterest/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BoardsRoute: typeof BoardsRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  KeywordsRoute: typeof KeywordsRoute
  LogsRoute: typeof LogsRoute
  OnboardingRoute: typeof OnboardingRoute
  PinsRoute: typeof PinsRoute
  ScheduleRoute: typeof ScheduleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SitesRoute: typeof SitesRouteWithChildren
  PagesIdRoute: typeof PagesIdRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  PagesIndexRoute: typeof PagesIndexRoute
  ApiPublicCronCrawlRoute: typeof ApiPublicCronCrawlRoute
  ApiPublicCronImagesRoute: typeof ApiPublicCronImagesRoute
  ApiPublicCronMaterializeRoute: typeof ApiPublicCronMaterializeRoute
  ApiPublicCronPinterestTokenRefreshRoute: typeof ApiPublicCronPinterestTokenRefreshRoute
  ApiPublicCronPublishRoute: typeof ApiPublicCronPublishRoute
  ApiPublicCronSerpRoute: typeof ApiPublicCronSerpRoute
  ApiPublicCronTierCheckRoute: typeof ApiPublicCronTierCheckRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicPinterestCallbackRoute: typeof ApiPublicPinterestCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pins': {
      id: '/pins'
      path: '/pins'
      fullPath: '/pins'
      preLoaderRoute: typeof PinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$id': {
      id: '/pages/$id'
      path: '/pages/$id'
      fullPath: '/pages/$id'
      preLoaderRoute: typeof PagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/style-setup': {
      id: '/sites/style-setup'
      path: '/style-setup'
      fullPath: '/sites/style-setup'
      preLoaderRoute: typeof SitesStyleSetupRouteImport
      parentRoute: typeof SitesRoute
    }
    '/api/public/cron/crawl': {
      id: '/api/public/cron/crawl'
      path: '/api/public/cron/crawl'
      fullPath: '/api/public/cron/crawl'
      preLoaderRoute: typeof ApiPublicCronCrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/images': {
      id: '/api/public/cron/images'
      path: '/api/public/cron/images'
      fullPath: '/api/public/cron/images'
      preLoaderRoute: typeof ApiPublicCronImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/materialize': {
      id: '/api/public/cron/materialize'
      path: '/api/public/cron/materialize'
      fullPath: '/api/public/cron/materialize'
      preLoaderRoute: typeof ApiPublicCronMaterializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/pinterest-token-refresh': {
      id: '/api/public/cron/pinterest-token-refresh'
      path: '/api/public/cron/pinterest-token-refresh'
      fullPath: '/api/public/cron/pinterest-token-refresh'
      preLoaderRoute: typeof ApiPublicCronPinterestTokenRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/publish': {
      id: '/api/public/cron/publish'
      path: '/api/public/cron/publish'
      fullPath: '/api/public/cron/publish'
      preLoaderRoute: typeof ApiPublicCronPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/serp': {
      id: '/api/public/cron/serp'
      path: '/api/public/cron/serp'
      fullPath: '/api/public/cron/serp'
      preLoaderRoute: typeof ApiPublicCronSerpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/tier-check': {
      id: '/api/public/cron/tier-check'
      path: '/api/public/cron/tier-check'
      fullPath: '/api/public/cron/tier-check'
      preLoaderRoute: typeof ApiPublicCronTierCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pinterest/callback': {
      id: '/api/public/pinterest/callback'
      path: '/api/public/pinterest/callback'
      fullPath: '/api/public/pinterest/callback'
      preLoaderRoute: typeof ApiPublicPinterestCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SitesRouteChildren {
  SitesStyleSetupRoute: typeof SitesStyleSetupRoute
}

const SitesRouteChildren: SitesRouteChildren = {
  SitesStyleSetupRoute: SitesStyleSetupRoute,
}

const SitesRouteWithChildren = SitesRoute._addFileChildren(SitesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BoardsRoute: BoardsRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  KeywordsRoute: KeywordsRoute,
  LogsRoute: LogsRoute,
  OnboardingRoute: OnboardingRoute,
  PinsRoute: PinsRoute,
  ScheduleRoute: ScheduleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SitesRoute: SitesRouteWithChildren,
  PagesIdRoute: PagesIdRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  PagesIndexRoute: PagesIndexRoute,
  ApiPublicCronCrawlRoute: ApiPublicCronCrawlRoute,
  ApiPublicCronImagesRoute: ApiPublicCronImagesRoute,
  ApiPublicCronMaterializeRoute: ApiPublicCronMaterializeRoute,
  ApiPublicCronPinterestTokenRefreshRoute:
    ApiPublicCronPinterestTokenRefreshRoute,
  ApiPublicCronPublishRoute: ApiPublicCronPublishRoute,
  ApiPublicCronSerpRoute: ApiPublicCronSerpRoute,
  ApiPublicCronTierCheckRoute: ApiPublicCronTierCheckRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicPinterestCallbackRoute: ApiPublicPinterestCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
